### ISSUE TITLE
VR but NO-CONTROLLERS (Vridge support)

### ISSUE THREAD

**Issue by cicatrice74** [bfeber/HLA-NoVR#101]
I would like to have this mod only for the controllers, 'cause i have "vr" using my phone and i would like to "only" use this mod to be able to play in vr but using keyboard and/or gamepad with it, not having hands controllers, is it already possible with this ?

**Comment by bfeber** [comment]
Due to how this project is using the default flatscreen source player character, I will never be able to do something like you described. Sorry.
