### ISSUE TITLE
Update discord link in README.md

### ISSUE THREAD

**Issue by DennisGHUA** [bfeber/HLA-NoVR#102]
The discord link has expired make sure to set the correct settings for the discord link so that it never expires:
By clicking "Edit invite link" under the link.
![image](https://user-images.githubusercontent.com/31701470/232253013-16a5748b-5d87-4802-838b-5973caccc5fb.png)
![image](https://user-images.githubusercontent.com/31701470/232253018-47cf8ee2-fa87-4156-a68e-1b4fcee8900d.png)

**Comment by bfeber** [comment]
Huh? Still works

**Comment by DennisGHUA** [comment]
I was getting this error. But after trying to opening it in incognito it works. So appears to be a issue on my end.
![image](https://user-images.githubusercontent.com/31701470/232253177-2aa2b43e-a91f-4c13-a10a-6c8737837946.png)
