### ISSUE TITLE
Play with ADDONS game crashes cannot continue

### ISSUE THREAD

**Issue by jflorian27** [bfeber/HLA-NoVR#107]
I downloaded the latest update and removed all previous saved positions in the game and when I start the game via add-ons, after the elevator scene the game crashes into windows every time.And here this file will be created after the game crashes F:\programy2\Half Life Alyx\game\bin\win64 hlvr_2023_0416_045837_0_accessviolation.mdmp.When I start the game without addons it doesn't do that and the game continues.
![Bez názvu1](https://user-images.githubusercontent.com/130433847/232266394-b39f9c5c-9f99-480a-9bce-a37b65cb51be.png)

**Comment by jflorian27** [comment]
And if the game crashes in the same place every time and you can't continue  which is annoying  turn off ADDONS hlvr_addons/novr/ and play without crashing the game and Right from the start of the new game.You can't just turn off ADDONS hlvr_addons/novr/ and continue from the last saved position because ADDONS hlvr_addons/novr/ is tied to the saved position information is written to it same when you play without ADDONS hlvr_addons/novr/ so you can't turn it on to load it into a running game where you have ADDONS hlvr_addons/novr/ turned off.Will there be a problem with saving the game somewhere because when using ADDONS on hlvr_addons/novr/ the game crashes when it should load and obviously save the location behind the elevator.

**Comment by jflorian27** [comment]
Here I am sending you a .mdmp file that you can examine, which every time the game crashes at this point I will do on the disk, of course it will have information stored in it as to why it is doing this and if you have the time and know about it then you would know where the problem is and could fix it or share with us that the problem is with me and what it is.Thank you so much for your help  
[hlvr_2023_0416_172431_0_accessviolation.zip](https://github.com/bfeber/HLA-NoVR/files/11243006/hlvr_2023_0416_172431_0_accessviolation.zip)

**Comment by bfeber** [comment]
I removed the addon by default since it was causing crashes, everything should be fine now with saves that don't have the addon enabled
