### ISSUE TITLE
3-Round Burst not working for Pistol upgrade

### ISSUE THREAD

**Issue by dragonhart6505** [bfeber/HLA-NoVR#111]
as it says in the title. purchasing 3RB in the upgrade station applies the visual alteration to the weapon but does not apply the burst-fire property

**Comment by bfeber** [comment]
> applies the visual alteration to the weapon
???
There is none

**Comment by dragonhart6505** [comment]
could've sworn the barrel/slide of the pistol changed when 3RB was added (when i played on Meta Quest 2)? if not, it's been a year since then so my mistake...but 3RB still doesn't work.

i've got a couple other issues i want to make sure haven't been mentioned yet regarding weapons and environment to point out. i know this is an ongoing project, it plays amazing btw! i didn't even finish it on Quest 2 and i'm about 3/4 through with very little issue

**Comment by dragonhart6505** [comment]
3RB works with alt-fire...nvm
