### ISSUE TITLE
Feature Request: Key press to activate/cook Grenades

### ISSUE THREAD

**Issue by dragonhart6505** [bfeber/HLA-NoVR#113]
Xen grenades more often than not won't even activate. made for a pain in the ass taking out the respawning poison headcrabs in the Northern Star, causing me to almost run out of ammo entirely because i kept falling back to bottom floor. skill issue, yes...but screw that elevator shaft jump in particular.

cooking a grenade in general was pretty vital in a lot of situations

**Comment by bfeber** [comment]
Fixed (they activate when moved to fast/thrown)
