### ISSUE TITLE
Grenade launcher attachment doesn't work

### ISSUE THREAD

**Issue by dragonhart6505** [bfeber/HLA-NoVR#114]
just...doesn't have a keybind i guess? alt-fire is just the double shot

**Comment by bfeber** [comment]
Middle click if you have a grenade

**Comment by dragonhart6505** [comment]
been tried that as well...no luck, latest zip

**Comment by dragonhart6505** [comment]
updated 3RB topic to note middle mouse button works on the pistol. does not on the shotgun grenade launcher

**Comment by bfeber** [comment]
try capping you FPS to 60 or 120

**Comment by dragonhart6505** [comment]
i already use vsync (as suggested) on a 60hz monitor

**Comment by dragonhart6505** [comment]
> try capping your FPS to 60 or 120

have removed vsync and artificially locked FPS, locked FPS + vsync, unlocked...not working. not saying you don't believe me, but would an example video help?

**Comment by dragonhart6505** [comment]
> try capping your FPS to 60 or 120

have made a recording including performance counter if you'd like. video also shows middle-mouse click for pistol is being inconsistent also

**Comment by bfeber** [comment]
Fixed
