### ISSUE TITLE
Suggestion: Look to survival horror, not just Half-Life

### ISSUE THREAD

**Issue by SnuggleBucketsNathan** [bfeber/HLA-NoVR#116]
I think that trying to translate Alyx VR to be as close to Half-Life is a mistake, the VR experience is clearly already inspired by survival horror games with the upgrades, slower pacing, looting and enemy encounters, a noVR mod should ask: 
"How do we translate the VR experience into a flatscreen experience?"
And for that, I can see 2 things that stick out.

1. Aiming should be a thing, not just default Half-Life hip firing, but keep the combat and upgrades still meaningful, meaning you should have something like Resident Evil 7/8, where hipfiring has no crosshair or a very large unfocused one and is extremely inaccurate - without the lasersight! - and you need to hit aim (mouse 2) to bring up a crosshair, and steady your aim, you'd move slower while aiming, and moving while aiming would bring "bloom" to the crosshair. 
That way the upgrades like the weakpoint highlight sight and lasersight would remain relevant, and it would keep the limited combat encounters still meaningful with more deliberate aiming required.
That way, once you do get the lasersight, hipfiring will feel like an upgrade, where you can reliably just shoot where the laser is which is present even when no aiming crosshair is, and don't need to aim deliberately anymore, though maybe it could still have its uses (definitely with weakpoint highlights)

2. Environmental manipulation could take some more queues from Amnesia/Penumbra/Soma, where you "grab" things and then move your mouse to move them, aim at a drawer handle and bring up a grab icon, hold mouse 1/E to grab to it, then move your mouse to slide the drawer open. grab the wheels then move mouse in a circle to crank them to open shutters and doors etc.
It would translate the deliberate environmental manipulation of a VR experience into a more tactile flatscreen experience.
(I think Penumbra/Amnesia/Soma are all pretty moddable, so maybe their code could be looked at to borrow some of their homework for scripting environmental/item/physics manipulations into Alyx flatscreen)

Those are the two big things, smaller things could be worth considering as well, like HUD, how to tell the player about things, maybe health shouldn't be a hud element, well, maybe it flashes on the screen when you take damage and then fades away, and to check health otherwise would bring your hand up to the screen like you're checking your watch.
Checking ammo should maybe make Alyx say how many shots are left if you're tapping reload and flash the hud element on screen, then hold reload to actually start reloading, making reloading still be a bit slower, more deliberate and more tense while in combat.

**Comment by SnuggleBucketsNathan** [comment]
I'm not talking about overhauling the game, that's the issue, the issue is that currently it looks like the modders are focusing on making this handle like Half-Life 1/2, with a clean HUD, with just pin perfect accuracy with weapons shooting where the crosshair is, and the thing is, the game is clearly more of a survival horror with how the zombies and combine and antlions work, so the controls need to fit that, the gun on the screen shouldn't be pin perfect accurate with a fixed crosshair, it should wobble around and move and presumably then that will also impact accuracy if it's still the physical gun inside the game world from the VR game anyway, voila, now hipfiring is inaccurate, then hold mouse to to lock the weapon at the center, bring up a crosshair, add some bloom when you move around, add a tiny bit of smooth zooming, slow the player speed, and you've translated a VR experience more accurately into a flatscreen experience where your aiming is more in tune with the rest of the game.

Somnst was already adding Amnesia/Penumbra/Soma like environmental manipulation, I think they even just straight up used the same HUD icons with the hand picture and arrows, so clearly that is already doable, it's been done, just not released.

I think tweaking aiming shouldn't be that hard and it would accommodate the rest of the games mechanics and pacing.

But you already voiced your disappointment with Alyx even in VR so I suspect that you will still maintain that the modders shouldn't bother period.
I disagree.

**Comment by dragonhart6505** [comment]
will you go away? this project is "Half Life: Alyx NoVR" not "Half Life: Alyx Change The Entire Game". it has ONE PURPOSE: make the game playable without a VR headset. you are literally talking about making and entirely different game. go to one of those projects then, quit flooding this one

**Comment by SnuggleBucketsNathan** [comment]
... What? I'm not talking about changing the entire game, are you talking to me or SpaceMageWhatever?

**Comment by dragonhart6505** [comment]
> ... What? I'm not talking about changing the entire game, are you talking to me or SpaceMageWhatever?

yup...forgot to quote, my bad

**Comment by SnuggleBucketsNathan** [comment]
> > ... What? I'm not talking about changing the entire game, are you talking to me or SpaceMageWhatever?
> 
> yup...forgot to quote, my bad

Ah, cool, no worries!

**Comment by dragonhart6505** [comment]
> i was kinda hoping...

will you go away? this project is "Half Life: Alyx NoVR" not "Half Life: Alyx Change The Entire Game". it has ONE PURPOSE: make the game playable without a VR headset. you clearly have a problem with Valve, not the mod creator.

**Comment by dragonhart6505** [comment]
> > > ... What? I'm not talking about changing the entire game, are you talking to me or SpaceMageWhatever?
> > 
> > 
> > yup...forgot to quote, my bad
> 
> Ah, cool, no worries!

(i have no idea how github comments work xD)

**Comment by dragonhart6505** [comment]
> > > i was kinda hoping...
> > 
> > 
> > will you go away? this project is "Half Life: Alyx NoVR" not "Half Life: Alyx Change The Entire Game". it has ONE PURPOSE: make the game playable without a VR headset. you clearly have a problem with Valve, not the mod creator.
> 
> thats super rude, im not allowed to, say my thoughts? i didnt say to change the whole game at all, i said the same exact thing? that the mod should focus on, making things playable and, then you can focus on overhauling the gameplay?
> 
> i was just rambling a bit, i dont know why you gotta be rude af

but this isn't an overhaul mod, it's a playability mod. your rambling does nothing but look like bitching. rude or not, the point stands: this is NOVR, not "make the game better"

**Comment by VladManyanov** [comment]
people are free to make their own gameplay & visual changes to novr mod, just it could be a different fork or script

**Comment by SnuggleBucketsNathan** [comment]
> people are free to make their own gameplay & visual changes to novr mod, just it could be a different fork or script

I'm not sure if this is in response to SpaceMageWhatever, but I want to hammer home the point of the topic, which is that if you look at the game, Alyx VR, where you need to focus on aiming with your hands, you by design as a shlubby gamer in a room are slower than a retro FPS Gordon Freeman sprinter and probably have a hard time multitasking, you aren't playing it like a movement shooter where you're bunnyhopping and circlestrafing while pulling off effortless headshots left and right-- Translating that to noVR, I think it goes against what the core game is to then make vanilla Half-life controls and aiming and feel, where aiming is just placing an accurate crosshair over an enemy and getting reliable results in a split second while clicking away and easily just circle strafing every enemy at a brisk movement speed.

If the game were to control like Half-Life 1/2, then slow AI and cramped locations and enemy encounter compositions will stick out as being in conflict with that, it's like if someone were to mod Resident Evil 7/8 to handle more like Doom 2016, where Ethan Winters could now suddenly jump around and move fast all the while his aiming is impeccable all the time, he doesn't need to hold down aim to focus the reticle and carefully plant those headshots anymore, he can easily just multitask sprint, strafe at full speed while aiming is as simple as move the mouse and click like it's Quake/Doom/Half-Life.
But then RE7/8 would feel laughable, because zombies are still slowly lumbering around braindead, and you'd still feel a level of clunk with the environmental design not being designed around being able to jump around easily and constantly just sprinting.

If you aren't overhauling AI and combat encounters and levels (which I'm saying you shouldn't anyway), then the controls should reflect the experience of the VR design, and a noVR mod of Alyx shouldn't just be a vanilla Half-Life control scheme, but in my opinion it should reflect the deliberate slow methological controls intended for that, and no better example can be found than regular survival horror, the FPS controls of something like Resident Evil 7/8/Alien Isolation for instance.

That's what I'm saying, don't overhaul the game, but don't make player handling that wasn't meant for Alyx either, noVR but still not losing everything about the VR design philosophy.
Alyx isn't Gordon Freeman.

**Comment by dragonhart6505** [comment]
idk if you noticed, but 3 dimensional interaction is a bit difficult on a 2D plain. this isn't Hand Simulator. what you're asking has been done, in fact. here's the problem: the controls are a problem. we don't have 6 hands to manipulate things on a keyboard/mouse like in VR...BECAUSE THIS ISN'T VR!!!! seriously...in this mod, have you tried holding breath and crouching at the same time? you're supposed to be able to do more but we CANNOT because WE AREN'T IN VR. i believe the intention (and so far execution) WAS to make this game play like Half Life and why is that such a terrible thing? i played in VR...fun stuff, cool to do, pretty fucking scary tbh. you know what i don't have anymore? a virtual reality headset and motion controls. i also don't have the dexterity or time awkwardly rotate 2 hands on a flat screen.

Half Life: Alyx NoVR is a FPS experience, first and foremost. it plays as such and works perfectly well. if you want a different experience, there is a proper mod for mouse and keyboard controls like in VR.

> ...it should reflect the deliberate slow methodical controls intended for that

i don't think we had the same experience in VR. this game was nuts to move around in and avoid taking damage. in the Jeff chapter, yes you should be slow. everywhere else i zipped around and dodged and hid and suppressed to get a better advantage. are you telling me i was playing this game wrong? no....i made my own experience out of it and so far i've had just as much of a good time playing like this.

> ...where aiming is just placing an accurate crosshair over an enemy and getting reliable results in a split second while clicking away and easily just circle strafing every enemy at a brisk movement speed

we clearly aren't having the same experience outside of VR, either. both the accuracy and movement speed are TRASH 😂

> Alyx isn't Gordon Freeman.

Gordon Freeman is a scientist become incredible badass with 0 prior training. Alyx Vance is a resistance fighter born into the world Freeman failed to save the first time and would be safe to assume could do far more than Gordon with her younger age and body type. but maybe we forget sometimes 

THAT THIS IS A FUCKING VIDEO GAME OMG WHAT THE HELL

**Comment by bfeber** [comment]
Interactions may be improved in the future and there will be ADS + more with weapon upgrades. But we won't make default aim terrible or something like that to make the game harder. That can be done in other ways.
