### ISSUE TITLE
Cheats are not working properly

### ISSUE THREAD

**Issue by CteXIII** [bfeber/HLA-NoVR#126]
-Impulse 101 - Doesnt give resins.Pistol magazine has 0 bullets and weapon is not reloading itself even when pressing R button. Pistol is unusuable after cheat.

-Impulse 102 - Not working at all.

-hlvr_shotgun_grant_upgrades 3 - Not working at all.

**Comment by bfeber** [comment]
> -Impulse 101 - Doesnt give resins.Pistol magazine has 0 bullets and weapon is not reloading itself even when pressing R button. Pistol is unusuable after cheat.
Use hlvr_addresources

> -Impulse 102 - Not working at all.
Use inv_flashlight

> -hlvr_shotgun_grant_upgrades 3 - Not working at all.
Will add a command for that in the future. But not all weapon upgrades are in yet (#25)
