### ISSUE TITLE
Crash to desktop on player death.

### ISSUE THREAD

**Issue by TonyH1234** [bfeber/HLA-NoVR#127]
Crashes to desktop instead of reloading save  when player dies. Was only happening occasionally early in the game but happening all the time  now I'm more than half way through.

**Comment by bfeber** [comment]
Official campaing? How much RAM/VRAM?

**Comment by fog13k** [comment]
> Official campaign without addons? How much RAM/VRAM?

I have the same problem, official campaign, 16Gb ram, GTX 1080 8gb

**Comment by duckhut33** [comment]
Same issue here. Official campaign with addons. 16gb ram, GTX 1060 6gb. Started happening with the Northern Star chapter with death resulting in total game crash. It is not a random issue and occurs every time. Tried changing video settings but doesn't make a difference whether on low, medium, etc. Still playing the game tho. Thanks for this great mod!!!

**Comment by xtr3mz** [comment]
crash to desktop at chapter 1 when combine electric shock alyx to black screen

**Comment by duckhut33** [comment]
It stopped crashing the last 2 chapters. I know this sounds strange but the crashes seemed to occur on the maps that were “outdoors”. Don’t know if there is any correlation. Just sayin.

**Comment by jazluvr449** [comment]
I'm having the same problem. I'm battling all the electric crabs and zombies in the "cave", and every time i die, it crashes to steam. Really frustrating. Script #7. AMD 5800x,  asus 3080 12gb. Everything else is stable. I have plenty of ammo, and novr map edits addon installed.

**Comment by xtr3mz** [comment]
https://www.moddb.com/mods/half-life-alyx-novr/downloads/half-life-alyx-novr-script-update-8

with update #8 mine is fine now.
