### ISSUE TITLE
game stutters a lot

### ISSUE THREAD

**Issue by jazluvr449** [bfeber/HLA-NoVR#130]
I have a good pc, amd 5800x, asus 3080, everything is very stable passes all stability test i throw at it, other games play great. Right now I'm stuck at superweapon, where you toss a grenade into the shaft that a headcrab opens. It doesn't open. i can't do anything except shoot all my ammo at nothing.

Never mind, i fixed it by restarting the chapter. no more stuttering, and the headcrab came out so i could throw my 'nade in the shift. The game is coming along really nicely! I love thew new animations. You guys are awesome! Great work, you should be proud. I'm @ Jeff now...I'm actually scared to play it...lol.

**Comment by bfeber** [comment]
Glad to hear!
