### ISSUE TITLE
Grenades Dupe When Looking away.

### ISSUE THREAD

**Issue by Jem20** [bfeber/HLA-NoVR#132]
On Chapter 4 there's a bug, I think. Basically, when you look away and turn back around more grenades spawn.

Before:
![Screenshot (283)](https://user-images.githubusercontent.com/68351730/235269471-2e6503db-ed18-4584-b156-1d81a1c03145.png)

After:
![Screenshot (284)](https://user-images.githubusercontent.com/68351730/235269535-232d04bd-1daf-4bdd-9959-897aa90f122b.png)

**Comment by bfeber** [comment]
that's from the game so you don't get softlocked. the grenades will be limited to the two wrist pockets soon

**Comment by Jem20** [comment]
Ah, alright.
