### ISSUE TITLE
difficulty options changes to normal after picking easy or other easy option.

### ISSUE THREAD

**Issue by jazluvr449** [bfeber/HLA-NoVR#136]
I can't get past the antlions in revelations heading to the shack. I can get there, just barely, but I'm completely overwhelmed by purple and other antlions, and combine shooting at me or throwing grenades. I can't pick them up (or fast enough) to throw them back. This is while I'm using the health station in the shack.

When i started this new game, I picked easy mode. This is very far from easy. It's not fun when i spend all afternoon reloading my save with full health and enough ammo.As soon as i jump into the yard and over the car, I'm overwhelmed. I die everytime, even though I make it to the shack. 

I watch utube vids, and their aren't nearly this many antlions to deal with. In vr or novr gameplay.

**Comment by bfeber** [comment]
Fixed

**Comment by jazluvr449** [comment]
Thanks B….I saw the issues I posted and you fixed them all, I don’t know what to do on GitHub, so I’m replying by email that I received your emails that the issues I posted are all fixed. Thank you!  If there is something I’m supposed to do to remove my issue, please tell me what to do in email….thanks again for all you do…thanks again for all you do! Sent from Mail for Windows From: Björn FeberSent: Monday, December 18, 2023 5:06 AMTo: bfeber/HLA-NoVRCc: jazluvr449; AuthorSubject: Re: [bfeber/HLA-NoVR] difficulty options changes to normal after picking easy or other easy option. (Issue #136) Fixed—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
