### ISSUE TITLE
Many problems

### ISSUE THREAD

**Issue by jazluvr449** [bfeber/HLA-NoVR#139]
please disregard since i can't delete.

**Comment by jazluvr449** [comment]
Yeah, I’m ok…a hug…lol. Sent from Mail for Windows From: SpaceMageWhateverSent: Wednesday, May 17, 2023 1:03 PMTo: bfeber/HLA-NoVRCc: jazluvr449; AuthorSubject: Re: [bfeber/HLA-NoVR] My issue is this game! (Issue #139) are u ok? do u need a hug or—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jazluvr449** [comment]
Don't get me wrong, i love what you guys are doing, much respect to you all, but I am having problems. Since you guys implemented the wristpockets, I can't equip my shotgun with a grenade. And I'm in arms' race, after killing the 1st gunner in the wharehouse, I'm supposed to get to a double door housing 4 zombies to kill, but it's like...a noclip area. 

I have screenshots on my steam homepage. My name there is just jazluvr, if you care to see them. I can't progress any further. Any help you can give would be much appreciated.

**Comment by jazluvr449** [comment]
> are u ok? do u need a hug or

or what....

**Comment by amolinae06** [comment]
> Don't get me wrong, i love what you guys are doing, much respect to you all, but I am having problems. Since you guys implemented the wristpockets, I can't equip my shotgun with a grenade. And I'm in arms' race, after killing the 1st gunner in the wharehouse, I'm supposed to get to a double door housing 4 zombies to kill, but it's like...a noclip area.
> 
> I have 2 screenshots on my steam homepage. My name there is just jazluvr, if you care to see them. I can't progress any further. Any help you can give would be much appreciated. I'm just really frustrated. Plus the game still crashes, but you state that is to be expected.

Then why do you open an issue.

**Comment by jazluvr449** [comment]
Your resonse looks like you only read the last sentence here. I have posted a few issues. I’m posting them to help, not criticize. Just yesterday I posted a work-around for an issue with the “noclip area, that another poster uploaded a screenshot of. And I’m using the last version, w/o the wristpockets.  I feel that….because we can’t teleport, we should have a bit of a balance, that we can store  grenades like pistol clips. Plus the grenade launcher still doesn’t work half the time, and I can’t the new launcher to work. I’ve unstalled the game completey and re-installed it and the novr add-on. Because I don’t know how to uninstall the mod, which you guys don’t tell us how. The only thing you tell us how to do anything is to install the mod. I can’t believe you asked me this. We are beta testers for you. Sent from Mail for Windows From: AlejandroSent: Wednesday, May 24, 2023 10:52 PMTo: bfeber/HLA-NoVRCc: jazluvr449; AuthorSubject: Re: [bfeber/HLA-NoVR] Many problems (Issue #139) Don't get me wrong, i love what you guys are doing, much respect to you all, but I am having problems. Since you guys implemented the wristpockets, I can't equip my shotgun with a grenade. And I'm in arms' race, after killing the 1st gunner in the wharehouse, I'm supposed to get to a double door housing 4 zombies to kill, but it's like..a noclip area.I have 2 screenshots on my steam homepage. My name there is just jazluvr, if you care to see them. I can't progress any further. Any help you can give would be much appreciated. I'm just really frustrated. Plus the game still crashes, but you state that is to be expected.Then why do you open an issue.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jazluvr449** [comment]
I didn't realize all this text would show up here by answering via email. Sorry about that. I'm new to these forums, (discord too), and don't know how to use them correctly.
@amolinae06, i post an issue because i am/was having issue. I solved it myself and posted it in discord for zorf, who posted a screenshot of the same problem, I'm here to help, not criticize, ok?
