### ISSUE TITLE
Main menu doesn't work on Linux

### ISSUE THREAD

**Issue by sbourdeauducq** [bfeber/HLA-NoVR#140]
The main menu cannot be opened when applying this mod to the Linux version, which among other things makes it impossible to start a game. (I assume this is a Linux-specific issue)

Quick work around if you just want to play:
```
diff --git a/game/hlvr/scripts/vscripts/novr.lua b/game/hlvr/scripts/vscripts/novr.lua
index ffa7fa8..d6d3907 100644
--- a/game/hlvr/scripts/vscripts/novr.lua
+++ b/game/hlvr/scripts/vscripts/novr.lua
@@ -526,6 +526,7 @@ if GlobalSys:CommandLineCheck("-novr") then
                 ent = SpawnEntityFromTableSynchronous("game_text", {["effect"]=2, ["spawnflags"]=1, ["color"]="140 140 140", ["color2"]="0 0 0", ["fadein"]=0, ["fadeout"]=0.15, ["fxtime"]=0.25, ["holdtime"]=10, ["x"]=-1, ["y"]=2})
                 DoEntFireByInstanceHandle(ent, "SetText", "NoVR by GB_2 Development Team", 0, nil, nil)
                 DoEntFireByInstanceHandle(ent, "Display", "", 0, nil, nil)
+                SendToConsole("map a1_intro_world")
             else
                 GoToMainMenu()
             end
```

**Comment by Hydranet** [comment]
> Quick work around if you just want to play:

Thanks!

That works! It would be great if the menu could be fixed for Linux because I can't save or load a game and currently quick saves and quick loads are for your current session and I haven't reached an auto-save checkpoint yet.

**Comment by Hydranet** [comment]
I talked to one of the devs on Discord. They said to remove -vsync, I still had the issue after that with the Linux runtime, I switched to a Proton version and then the menu worked as expected and the menu wasn't flickering either.

**Comment by OzFalcon** [comment]
> I talked to one of the devs on Discord. They said to remove -vsync launch option, I still had the issue after that with the Linux runtime, I switched to a Proton version and then the menu worked as expected and the menu wasn't flickering either.

Adding to this, I tried using -novsync option and it accepted the option and now HLA was rendering 120fps (with Vulcan).
While it did make the menu more visible and somewhat usable, The same problem still exists.

Initially I just tried proton and the windows version did display the menu correctly @ 120fps with Vulcan.
But I'd prefer the native Linux obviously.

**Comment by bfeber** [comment]
Try the new launcher Linux version
