### ISSUE TITLE
Cant drop batteries from wrist!

### ISSUE THREAD

**Issue by Geskawary234** [bfeber/HLA-NoVR#144]
Probably some script broke, but how do i fix it? Like i literally checked keybinds and wrist script and i defenetly press the right button but still it wont drop!

**Comment by Geskawary234** [comment]
checked, it only happens with batteries

**Comment by auex01** [comment]
The wrist pockets broke by chapter 5 for me. Can't drop anything that's in them. As for batters, use the console command item_hlvr_prop_battery and it'll spawn a battery where you're looking.

**Comment by OzFalcon** [comment]
I think I had something like this.
Battery was in top position, Medics was in bottom position.
I was full health and when I tried to get the battery it just beeped like I was trying to use the medics with full health.
Is there some way to switch the wrist items. And I presume there are only two wrist slots.

**Comment by bfeber** [comment]
Fixed
