### ISSUE TITLE
BUG: at the very beginning I am able to jump over the balcony

### ISSUE THREAD

**Issue by FarmerKarwer** [bfeber/HLA-NoVR#164]
![image](https://github.com/bfeber/HLA-NoVR-Launcher/assets/83603595/32837378-577d-4de2-8117-b39a72f19935)

![image](https://github.com/bfeber/HLA-NoVR-Launcher/assets/83603595/0e91a053-2a1b-4aca-a73e-133481d2edc5)

![image](https://github.com/bfeber/HLA-NoVR-Launcher/assets/83603595/48c0bd70-9b82-4c88-903a-123aa6f5be2f)

**Comment by FarmerKarwer** [comment]
The same with the second balcony (it is lower)

![image](https://github.com/bfeber/HLA-NoVR/assets/83603595/c525a0df-f3be-4bc0-8d17-8d566da4cff9)

**Comment by bfeber** [comment]
Fixed
