### ISSUE TITLE
BUG: got stuck in a door

### ISSUE THREAD

**Issue by FarmerKarwer** [bfeber/HLA-NoVR#166]
I stood up here and tried to close the door
![image](https://github.com/bfeber/HLA-NoVR/assets/83603595/b8763269-e3e3-428d-848d-feac5d0a77eb)

As a result, I got stuck:

![image](https://github.com/bfeber/HLA-NoVR/assets/83603595/8a249f59-57f2-4cb4-b4d2-2cc35146fd9e)

**Comment by bfeber** [comment]
Unstuck is better now
