### ISSUE TITLE
BUG: I can go out of the map in Chapter 1

### ISSUE THREAD

**Issue by FarmerKarwer** [bfeber/HLA-NoVR#167]
![image](https://github.com/bfeber/HLA-NoVR/assets/83603595/1efa115b-e3de-4256-8591-0567f31b3382)

![image](https://github.com/bfeber/HLA-NoVR/assets/83603595/420f1c51-df4b-4e65-8434-8c618bbe542f)

![image](https://github.com/bfeber/HLA-NoVR/assets/83603595/f666a3f9-d8b3-4d8c-b524-5f95e695b1eb)

![image](https://github.com/bfeber/HLA-NoVR/assets/83603595/9fa6c8bb-520a-4a56-a3d5-82269ecae449)

![image](https://github.com/bfeber/HLA-NoVR/assets/83603595/9be632a1-61ae-48f1-8283-eec45eaaf598)

![image](https://github.com/bfeber/HLA-NoVR/assets/83603595/3a1c5f1d-e133-4e1f-8efc-6b1d9b2c1c5f)

![image](https://github.com/bfeber/HLA-NoVR/assets/83603595/3ef74f5b-45b0-44ef-b2d9-478ccab56a43)

**Comment by bfeber** [comment]
Fixed
