### ISSUE TITLE
Serious BUG: When I come to the Russel's house in Chapter 1, I see THIS

### ISSUE THREAD

**Issue by FarmerKarwer** [bfeber/HLA-NoVR#168]
![image](https://github.com/bfeber/HLA-NoVR/assets/83603595/ba6c65fc-df1f-4d22-a884-84bcc8d8eb9a)

![image](https://github.com/bfeber/HLA-NoVR/assets/83603595/8d147967-2252-42ab-bfb6-2979096670f7)

**Comment by bfeber** [comment]
Fixed
