### ISSUE TITLE
Combine Fabricator are non-interactable

### ISSUE THREAD

**Issue by LauraWebdev** [bfeber/HLA-NoVR#18]
You cannot interact with the combine fabricator whatsoever.

**Comment by VladManyanov** [comment]
As mod-maker said, fabricator & weapon upgrades support is not implemented yet

**Comment by LauraWebdev** [comment]
@VladManyanov I'm aware, I've created the issue to potentially track progress or at least show others it's in the works (as per #13 )

**Comment by bfeber** [comment]
Fuxed
