### ISSUE TITLE
Movement velocity not normalized

### ISSUE THREAD

**Issue by recore67** [bfeber/HLA-NoVR#184]
pressing either w+d or w+a will make you walk faster than just wasd independently, I'm guessing the vector magnitude is not normalized (returning 2 instead of 1). But I think this is an issue with the existing novr player movement system, idk decided to report eitherways.

**Comment by bfeber** [comment]
I have tried to fix this before, no luck. Not a big deal though, since you can't go faster than sprint speed anyways
