### ISSUE TITLE
Arrow key capture in LUA

### ISSUE THREAD

**Issue by BeneFalcon** [bfeber/HLA-NoVR#189]
I'm trying to capture the arrow keys for movement in bindings.lua. So far without success. Do you happen to hape a script for this?

Thanks in advance

**Comment by bfeber** [comment]
A simple search gives you the Valve Developer Wiki as a result, where you can find all the key names: https://developer.valvesoftware.com/wiki/Bind#Special_Keys

**Comment by BeneFalcon** [comment]
Thank you, i was looking in the wrong place. Your help is much appreciated.
