### ISSUE TITLE
Binding console commands

### ISSUE THREAD

**Issue by ertup0** [bfeber/HLA-NoVR#190]
Every time I try to bind a console command to a key (for example "bind n ent_text") it gets reset on map load or game restart
Is it possible to bind it using some kind of config? from my testing bindings.lua doesn't bind console commands

**Comment by bfeber** [comment]
![grafik](https://github.com/bfeber/HLA-NoVR/assets/16156986/84afcaac-9eeb-4f5b-a5fc-95936c33861e)
I created a note in novr.lua
