### ISSUE TITLE
Can't insert weapons into fabricator

### ISSUE THREAD

**Issue by LeiteLixo** [bfeber/HLA-NoVR#191]
After the update which made the multitool usable, weapons cannot be inserted into the fabricator. When returning to an older version, before the inclusion of the multitool, the fabricator works normally.

**Comment by bfeber** [comment]
Fixed

**Comment by gmankab** [comment]
i think i have same issue on latest version (nov 20)

**Comment by gmankab** [comment]
i was wrong, it working
