### ISSUE TITLE
Suggestion: Add a viewmodel fov setting

### ISSUE THREAD

**Issue by LeiteLixo** [bfeber/HLA-NoVR#195]
I think it would be useful to have a viewmodel fov setting separate from the overall fov. I don't know if this would be possible, but currently when using an fov of 90, which I find to be best, the arms are too far into the screen, as you can see in the attached screenshot.
![hla_viewmodel_fov90](https://github.com/bfeber/HLA-NoVR/assets/92181138/dda84ea0-db4f-4958-8f79-043245503100)

**Comment by bfeber** [comment]
The Half-Life: Alyx engine branch sadly doesn't render the viewmodel separately, so basically impossible
