### ISSUE TITLE
Cannot access wrist pockets as described in the ReadMe

### ISSUE THREAD

**Issue by WynandSmall19** [bfeber/HLA-NoVR#196]
Hi there

I'm a little late to the Half Life Alyx No VR hype and at the moment I don't find any assistance online relating to your mod about the above issue.

The key bindings you have listed in the ReadMe.md file does not work in-game.

Kindly confirm if the Wrist Pocket feature in your mod is currently disabled? Which means if I need to carry items across levels, do I have to use the E button to carry one item at a time?

![Capture](https://github.com/bfeber/HLA-NoVR/assets/135338757/ab85ad73-1d3c-4ed9-84d8-ee1bc110a04e)

**Comment by bfeber** [comment]
You are correct, the wrist pockets are currently disabled due to game breaking bugs, once they are fixed (soon) they will get re-enabled.
