### ISSUE TITLE
Fail to Quick Load before the Main Menu appear

### ISSUE THREAD

**Issue by pigmich** [bfeber/HLA-NoVR#199]
When press F9 to perform Quick Load function before the Main Menu shown (Or during the Valve Logo screen appear), the character was unable to move by using mouse, and the Mouse Cursor was disappeared when press "Esc" to access to the Menu.

**Comment by bfeber** [comment]
Yeah, I know about this bug. Just wait until the menu is loaded

**Comment by bfeber** [comment]
Fixed. You can also use the launch option "-novid" btw
