### ISSUE TITLE
Full screen mode is gone

### ISSUE THREAD

**Issue by forman** [bfeber/HLA-NoVR#203]
I can no longer play full screen and there is also no Graphics setting (anymore?) that would allow me to switch from windowed fixed size mode to full screen.

However, thanks for this mod!

**Comment by bfeber** [comment]
Don't use fullscreen. Just put your screen resolution in the launch options.

**Comment by forman** [comment]
@bfeber great, thanks. It also works by just not specifying `-w` and `-h`.

![image](https://github.com/bfeber/HLA-NoVR/assets/206773/c05ba8c7-50a3-4550-93e3-bd674051043e)

**Comment by bfeber** [comment]
I'm curious, was it not your actual resolution? Do you have multiple monitors or is display scaling enabled?

**Comment by forman** [comment]
> I'm curious, was it not your actual resolution?

No, it was less. And here is why:

![image](https://github.com/bfeber/HLA-NoVR/assets/206773/1d6b35ff-19df-451c-b032-7d1b4a9b716e)

**Comment by bfeber** [comment]
As I suspected. Will be fixed
