### ISSUE TITLE
HLA/NOVR only opens in window after update

### ISSUE THREAD

**Issue by BeeMerMon** [bfeber/HLA-NoVR#205]
I haven't played for a while, an update was applied at the last game restart and now the game only opens in a window. The game launch screen is now very limited in functionality also. Any help would be greatly appreciated, Thanks.

**Comment by donizettilorenzo** [comment]
And mouse tracking doesn't work, so we can't navigate menu

**Comment by forman** [comment]
Maybe #203 helps.

**Comment by bfeber** [comment]
You need to use the launcher
