### ISSUE TITLE
Viewmodel stutter at fast mouse movement and high framerate

### ISSUE THREAD

**Issue by fog13k** [bfeber/HLA-NoVR#211]
I noticed this when i changed my monitor, it seems like the viewmodel animations are not tied to framerate and therefore they can feel a bit stuttering especially at fast mouse movement when the rest of game is very smooth.
I don't what's the issue exactly, but this would be good to check this

**Comment by bfeber** [comment]
I know. I don't think there's a way to fix this unless you hack into the game's executable. VScript doesn't run every frame.
