### ISSUE TITLE
BUG - Black Screen with Sound- 27.12.2023 

### ISSUE THREAD

**Issue by BlackCry88** [bfeber/HLA-NoVR#215]
HLA No VR Mod - Black Screen - 27.12.2023
Hallo, Ich habe einen schwarzen Bildschirm und höre nur Musik und Geräusche wenn ich das Game Starte. Tab ich raus mit ALT+Tab dann sehe ich das Spiel richtig. Aber sobald ich wieder reingehe dann habe ich einen Black Screen. Ich benutze die neuste Version des Mods.

Hello, I have a black screen and only hear music and noises when I start the game. If I tab out with ALT+Tab then I can see the game properly. But as soon as I go back in I have a black screen. I'm using the latest version of the mod. 

![Unbenannt - Kopie - Kopie](https://github.com/bfeber/HLA-NoVR/assets/155065346/c8fdabfd-b642-4911-9807-962bf86bc2c8)

**Comment by bfeber** [comment]
Probably fixed
