### ISSUE TITLE
Number keys and scroll wheel not working to select weapons - Dec 27 version - Win 10

### ISSUE THREAD

**Issue by waterdog88** [bfeber/HLA-NoVR#219]
Pressing a number key at the top of the keyboard or using the scroll wheel doesn't change weapon to the selected weapon.  The correct weapon silhouette appears at the top of the screen but the weapon isn't selected.  The Q key works to quick change to the last weapon used.  Can't get back to the multi-tool now.  Latest update to Alex installed, using noVR Launcher, Dec 27 on Win 10.  Custom key bindings set for left hand use (all others use default): PRIMARY_ATTACK    = "MOUSE2"
SECONDARY_ATTACK  = "MOUSE1"
TERTIARY_ATTACK   = "MOUSE3"
QUICK_SWAP        = "Q"
MOVE_FORWARD      = "UPARROW"
MOVE_BACK         = "DOWNARROW"
MOVE_LEFT         = "LEFTARROW"
MOVE_RIGHT        = "RIGHTARROW"
JUMP              = "/"  Side note: what is binding identifier for <ALT-R> key?  Binding ALT key only affects <ALT-L>.  Thanks.

**Comment by bfeber** [comment]
Once a weapon is highlighted you need to press Primary Attack to select it. If it doesn't work you'll have to tell me what the command "bind MOUSE2" output in the console. As for your last question, I'd need to know your keyboard layout.

**Comment by waterdog88** [comment]
Thanks.  That worked for changing weapons.

I hadn't realized that the forum removed stuff in brackets so my key binding question didn't make sense.  I would like to bind the jump command to the right ALT key.  Using JUMP = "ALT" only affects the left ALT key.

While I'm here, how does one activate a grenade before throwing?  I get a buzzer noise when pressing the G key.

Thank you so much for all the work on this mod.  It is impressive.

**Comment by bfeber** [comment]
Use JUMP = "RALT". Grenades need to be in your wrist pocket to throw them
