### ISSUE TITLE
BUG - Can't open combine locker (containers) 

### ISSUE THREAD

**Issue by screenreel** [bfeber/HLA-NoVR#222]
When I'm trying to open the locker with multitool, the hologram appears, but I can't do anything. The container won't open, and I can't move the mouse. The mouse is stuck regardless of whether I load another save or start a new chapter. I have to restart the game. It doesn't happen randomly. It happens always when I'm trying to open the container.
here is the video:
https://youtu.be/si-mCLbMseM

**Comment by bfeber** [comment]
Are you using the launcher? I can't see it in the recording

**Comment by screenreel** [comment]
Sure **HLA-NoVR-Launcher.exe** 
Should I place **HLA-NoVR-Launcher-December_27th** folder in any specific location?
Also when I press mouse with multitool, red and blue dots appearing, they are not visible in the video, here is the screenshot.
this hologram and dots are visible even if a go far from container or load save or start the new game and mice is unresponsive as I mentioned above.

![Untitled](https://github.com/bfeber/HLA-NoVR/assets/70162227/fc92ac88-f47f-4938-8380-04d83ddfea75)

**Comment by bfeber** [comment]
You need to drag one blue dot to the other one without touching the red ones.

**Comment by bfeber** [comment]
I will add a tutorial for this
