### ISSUE TITLE
Chapter 2 multitool bug (cant enter quarantine zone)

### ISSUE THREAD

**Issue by SplashAddict** [bfeber/HLA-NoVR#223]
Whenever I am interacting with the machine on the wall with my multitool blue and red dots appear on the screen and I cannot do/interact with anything. I currently cant progress with the game because of this, fix would be much appreciated.
![HLA](https://github.com/bfeber/HLA-NoVR/assets/156413525/b70286e0-cf3d-42dc-94ef-0d069b079bb4)

**Comment by screenreel** [comment]
You have to connect two blue dots with your mouse without touching the red ones

**Comment by bfeber** [comment]
This will have a tutorial very soon
