### ISSUE TITLE
Bug - Combine container puzzle (Chapter 5) Blue and Red dots are overlapped by default

### ISSUE THREAD

**Issue by screenreel** [bfeber/HLA-NoVR#226]
Chapter 5
When you use multi tool on the container and hologram appears, one blue and one red dots are overlapped by default and it's hard to connect second blue dot with this one. You have to move mice fast.

![dsa](https://github.com/bfeber/HLA-NoVR/assets/70162227/fa1c4503-26fe-4d68-a81d-6122fb476f65)

**Comment by TheEpicTimmy** [comment]
Thanks, I managed to do this.

**Comment by bfeber** [comment]
I have removed the puzzle for now
