### ISSUE TITLE
Bug - Chapter 4 Puzzle requires bruteforcing (Blue dot overlaps with Red)

### ISSUE THREAD

**Issue by AdminProductions** [bfeber/HLA-NoVR#232]
This type of issue has already been brought up for Chapter 5, but it happened with me on Chapter 4.
This is what the dots look like when I go to use the tool.
![unsolvable puzzle](https://github.com/bfeber/HLA-NoVR/assets/72920461/3d7b3d46-a1e0-4371-aa00-6fcc4dfd1360)

EDIT: I managed to solve it, but because of the way that red dots work, I kept getting the blue dot stuck numerous times.
I had to brute force the dots to connect to solve it.

**Comment by screenreel** [comment]
same post is already opened: https://github.com/bfeber/HLA-NoVR/issues/226

**Comment by bfeber** [comment]
true
