### ISSUE TITLE
Bug - HLA freezes when trying to open canister with multi-tool, blue/red dots

### ISSUE THREAD

**Issue by loopytrixie** [bfeber/HLA-NoVR#237]
When trying to open the canister at the quarantine hatch, all play action freezes. Can still use the mouse and open the HLA-NoVR menu to quit the game, but I can't move Alyx or continue the game. Looks like this:
![HLA-NoVR-canister-bug](https://github.com/bfeber/HLA-NoVR/assets/161167747/532157c2-bde7-4d41-a168-d6553d095f99)

VConsole log:
![VConsole2 (64-bit) 2_24_2024 2_54_43 PM](https://github.com/bfeber/HLA-NoVR/assets/161167747/e8249e3a-d854-4427-9b25-a3002189a5df)

Gameplay video [here](https://photos.app.goo.gl/9hyWjPcAhEZNL8Sb9)

**Comment by sgjohnson1981** [comment]
I'm having the same issue.

**Comment by sgjohnson1981** [comment]
I realized this is a feature, not a bug. This is the NoVR way of solving these puzzles. My issue was the first time around the alternative instructions (to move a blue dot to touch the other blue dot without touching any red dots) didn't pop up.

**Comment by loopytrixie** [comment]
@sgjohnson1981 Fair enough, except that I can only move one of the blue dots (the one in the upper left-hand corner) and the plane of movement is restricted on all sides, meaning I have no way of moving the left do to the right without running into the edge of a red circle first. Any ideas?

**Comment by sgjohnson1981** [comment]
Nope. I ran into a few canisters like that later in the game but none of
them contained anything necessary to continue. Though I didn't try grabbing
the other blue dot. If I recall, that section needs a battery to open the
gate. Seems there's a cheat to drop a battery you can then pick up. Never
tried it though. I think the add-on requires its own implementation of
cheats and if not implemented it won't work.

**Comment by loopytrixie** [comment]
LOL as soon as you responded to this, I gave the game another try... The blue dot puzzle that came up was totally solvable this time, so I was able to get the battery to enter the quarantine zone. This is, of course, after I looked up the command to spawn it.
