### ISSUE TITLE
Suggestion: Add item manipulation in hands

### ISSUE THREAD

**Issue by GhostTown110489** [bfeber/HLA-NoVR#43]
Taking any object in hand, by means of the default key "E", so that it can be manipulated - that is, rotated in different directions. 

We pick up any object, as an example, let it be a mug. While the item is in the hands, scrolling the mouse wheel up / down, the item will rotate accordingly, up / down. And if at the same time hold down the right mouse button and start turning the mouse wheel up / down, then the object will already rotate horizontally to the right / left. And also, while the item is in the hands, if you hold down the "Z" key and start turning the mouse wheel up / down, the item will be pulled towards Alyx or move away from it. 

Such manipulation with objects in the hands would greatly simplify the task of obtaining the "Good Grub" achievement - turned the container with food into the right position, shook it over the jar with the Snark's, and now the achievement has been received. 

That such interactivity - the manipulation of objects in the hands, in general, should not interfere with the gameplay in any way while the player is moving along the storyline.

**Comment by bfeber** [comment]
I don't know how possible this is with the default Source grabbing system, so for now doing things like rotating the food container for the snark upside down automatically when grabbing could be a workaround

**Comment by kakahost** [comment]
In GMod this is done by Lua, maybe C++ can be possible too. Idk.

**Comment by bfeber** [comment]
Ok, I tried to do this, but it doesn't seem like this will be possible for now. The game code forces the object to lock into the right position and rotation automatically, can't really change anything about that with scripting.

**Comment by Kein** [comment]
Bumping this.
