### ISSUE TITLE
Pistol stops working after using the command Impulse 101

### ISSUE THREAD

**Issue by cat-thing** [bfeber/HLA-NoVR#44]
The pistol refuses to reload after using the Impulse 101 command, I have no clue why.

**Comment by VladManyanov** [comment]
you can select other weapon and switch to pistol back, seems impulse 101 gives some additional glitched weapon which looks like pistol on the same slot

**Comment by cat-thing** [comment]
Thanks for the help, it appears that the weapon in question is probably a broken revolver, as I believe that shared the same area in HL2.
