### ISSUE TITLE
a3_c17_processing_plant bugs

### ISSUE THREAD

**Issue by occune** [bfeber/HLA-NoVR#51]
- Health station right before the distillery makes you stuck in one place during the healing process

![image](https://user-images.githubusercontent.com/9035722/230758663-df801209-af8d-4c5f-9d48-1bc39345b3bf.png)

- The moving platform missing all the collision except for the wooden pallet and the concrete bag

![image](https://user-images.githubusercontent.com/9035722/230758794-dd51f4cd-c6ee-4b58-a945-fc2101617baf.png)

- Covering your mouth would not show Alyx's hand, only removes your viewmodel (intentional?)

**Comment by bfeber** [comment]
The first one is intentional for all health stations, going to fix the other 2

**Comment by bfeber** [comment]
fixed
