### ISSUE TITLE
Spawn the Camera in the Menu at a Closer Spot

### ISSUE THREAD

**Issue by SpaceMageWhatever** [bfeber/HLA-NoVR#58]
the menu right now is too far away, here's the setting i use, it's less awkward and it feels more polished

novr.lua
    function GoToMainMenu(a, b)
        SendToConsole("setpos_exact 817 -80 -26")
        SendToConsole("setang_exact 0.4 0 0")

**Before**
![](https://i.imgur.com/QkRKdoc.jpeg)

**After**
![](https://i.imgur.com/GDfWA0z.jpeg)

**Comment by SpaceMageWhatever** [comment]
here's another angle where the camera is centered to show the logo better
    function GoToMainMenu(a, b)
        SendToConsole("setpos_exact 818 -80 -26")
        SendToConsole("setang_exact 0.5 6.5 0")

![immagine](https://user-images.githubusercontent.com/130518753/231320125-79d9e971-21e4-4f71-86ff-6733e3fb8f90.png)

**Comment by bfeber** [comment]
Fixed
