### ISSUE TITLE
Add a Batch File to Start the Game, With Some Default Command Lines

### ISSUE THREAD

**Issue by SpaceMageWhatever** [bfeber/HLA-NoVR#59]
bundle the mod with this batch file to make things easier for people

create a batch file called Play.bat and paste these commands in it
`game\bin\win64\hlvr.exe -novr -vsync -novid +volume_fog_disable 1 -console -vconsole`

![](https://i.imgur.com/VSOEqB2.png)

**Comment by bfeber** [comment]
Fixed
