### ISSUE TITLE
Weapon Enhancement Device

### ISSUE THREAD

**Issue by jflorian27** [bfeber/HLA-NoVR#60]
Weapon Enhancement Device when I insert a weapon into it and the menu for weapon upgrade appears so if I don't put 9 cancel and I don't select anything quickly from the menu then when the menu disappears I can't take my weapon back from the weapon upgrade device.Even if I press the E button there.Unfortunately I can put the last saved position so that the menu doesn't disappear or I put 9 cancel and take the weapon out of the device before the menu disappears.

**Comment by defkev** [comment]
Update to the latest Master which replaces the OSD with an interactive console.

The fabricator (in the subway) is bugged tho, i can put the pistol in, do the upgrade but then can't take it out again...tried jumping on the thing and quickly tapping E, nothing works.
Furthermore i can't use the fabricator again after interacting with it, put pistol in, tap Cancel, pistol goes back in my inventory and can't be put in again.

**Comment by bfeber** [comment]
> The fabricator (in the subway) is bugged tho, i can put the pistol in, do the upgrade but then can't take it out again...tried jumping on the thing and quickly tapping E, nothing works. Furthermore i can't use the fabricator again after interacting with it, put pistol in, tap Cancel, pistol goes back in my inventory and can't be put in again.

I just tested this and can't reproduce any of those issues

**Comment by defkev** [comment]
Second fabricator in the catacombs (past the shotgun) works.

**Comment by bfeber** [comment]
I tried the first one and it also works. Did you try a new save file?

**Comment by defkev** [comment]
No, came here to update in hopes it was fixed in Master.
It's not like its a game breaking bug or anything, just skipped it and upgrade at the next :shrug:

**Comment by bfeber** [comment]
should be fixed now

**Comment by bfeber** [comment]
...now
