### ISSUE TITLE
Object Pickups Are Too Far Away (No Glove)

### ISSUE THREAD

**Issue by SpaceMageWhatever** [bfeber/HLA-NoVR#61]
please move the objects closer to the camera, they are too awkward to use
![](https://i.imgur.com/Hl57t2R.jpeg)

picking up bottles or other objects feels too clunky or imprecise, i end up smashing most bottles by accident in the world
![](https://i.imgur.com/kSukdBa.jpeg)

something more like this, closer to my face
![](https://i.imgur.com/kOFeDCY.jpeg)

**Comment by bfeber** [comment]
Fixed
