### ISSUE TITLE
Flashlight Artefacts

### ISSUE THREAD

**Issue by SpaceMageWhatever** [bfeber/HLA-NoVR#63]
there are black spots all over the light
![](https://i.imgur.com/khsJgkx.png)
![](https://i.imgur.com/UsrXGIc.jpeg)

for some reason if you crouch it temporarily fixes it, then it breaks again

**Comment by bfeber** [comment]
main branch?

**Comment by SpaceMageWhatever** [comment]
yes

**Comment by SpaceMageWhatever** [comment]
> main branch?

it doesnt artefact as much up close in the flashlight branch but there are still artefacts in the distance, maybe i did something wrong when i set it up
