### ISSUE TITLE
Chapter 1 - Add a Trigger to Answer the Call, By Using E on the Monitor (Extra: Add a Tutorial Prompt, That Tells You, "Push E to Interact")

### ISSUE THREAD

**Issue by SpaceMageWhatever** [bfeber/HLA-NoVR#65]
add a trigger so that players can answer the call by pushing E on the screen too, this should help people who get stuck on this part, who dont realize that you need to aim down, im not the only one who tried to answer it by selecting the screen, i hope xD
![](https://i.imgur.com/Xummw6K.png)

**Comment by Jeff-xxx** [comment]
![2023_04_12_20-0448](https://user-images.githubusercontent.com/93405549/231479949-b2d88e66-5297-4f95-b153-778e15e3cde6.jpg)

**Comment by bfeber** [comment]
> ![](https://camo.githubusercontent.com/bfc4b48c0bed8efa03e605f091121df39b8fb8f4da236c5b498d5855cbb009d8/68747470733a2f2f692e696d6775722e636f6d2f6b6559474c70322e706e67)

Tbh, I think this ruins the immersion. This much extra info was never needed in a Half Life game. Its simplicity is what makes it great

**Comment by SpaceMageWhatever** [comment]
> > ![](https://camo.githubusercontent.com/bfc4b48c0bed8efa03e605f091121df39b8fb8f4da236c5b498d5855cbb009d8/68747470733a2f2f692e696d6775722e636f6d2f6b6559474c70322e706e67)
> 
> Tbh, I think this ruins the immersion. This much extra info was never needed in a Half Life game. Its simplicity is what makes it great

meh, im just pointing out the problems ¯\_(ツ)_/¯

**Comment by bfeber** [comment]
Ok, the first thing to interact with could get a tutorial.
But I think some people could stuck because the mod wasn't working properly

**Comment by bfeber** [comment]
Fixed
