### ISSUE TITLE
Chapter 1 (Soft Lock): Russel Doesn't Give Alyx More Ammo, If You Run Out, When You Get The Pistol

### ISSUE THREAD

**Issue by SpaceMageWhatever** [bfeber/HLA-NoVR#66]
i dont know if this was fixed but when i got to the part where Russel gives you the gun, i wasted all the bullets and i soft locked myself, and i had no ammo left, also for some reason when i reloaded the save my gun dissapeared? russel also did not give me any ammo so that i could open the locked door

**Comment by bfeber** [comment]
Fixed
