### ISSUE TITLE
Softlock in Fairview

### ISSUE THREAD

**Issue by Vivalzar** [bfeber/HLA-NoVR#70]
At the Fairview train station, near the end of **chapter 3** (I guess), it's impossible to pick the circular item up. When I press `E`, it rotates on itself, like if it already were in the terminal.

![image](https://user-images.githubusercontent.com/29254513/231553858-3dc29e95-37f5-4c7a-b049-9701ae7abc50.png)

**Comment by Vivalzar** [comment]
The bug seems to trigger when the player put the battery in the terminal. Before that, the round item can be picked up normally, but not after. And it's then impossible to put it in the machine.

**Comment by bfeber** [comment]
Fixed
