### ISSUE TITLE
Cannot call the lift up

### ISSUE THREAD

**Issue by geotavros** [bfeber/HLA-NoVR#71]
Found the blue card, killed headcrabs that spawn near lift. I assume I need to go down using this lift, but cannot call it by pressing E.
Reloading game doesn't fix this issue.

![20230413021313_1](https://user-images.githubusercontent.com/2202923/231607239-19217244-7a95-4e9b-9e9d-e5b87f51109f.jpg)

**Comment by geotavros** [comment]
On youtube I saw that lift is not supposed to be closed. 
Reloaded the autosave prior to moving up. Now the lift stays open. Don't know how it happened that it got closed and moved down.
This issue probably can be closed. Unless you want to try to reproduce it.

**Comment by bfeber** [comment]
I'll try to reproduce it
