### ISSUE TITLE
Weird Lever Puzzle Doesn't Work? Am I Stupid? Missing Ladder Teleport Clip

### ISSUE THREAD

**Issue by SpaceMageWhatever** [bfeber/HLA-NoVR#73]
i dont know what im supposed to do at this puzzle, but theres a room with two levers in it, when i pull one lever, one of the pallets on the right goes up and thats it, i cant do anything else on it, it just keeps glitching out 

if i use the left lever it gets stuck on the pipe, and it also feels glitchy to use, is this puzzle broken?

also theres a ladder under the puzzle area which cannot be used, i had to noclip to reach the top

**Comment by bfeber** [comment]
> if i use the left lever it gets stuck on the pipe, and it also feels glitchy to use, is this puzzle broken?
The puzzle is to use the hanging button controls to move the pipe.

> also theres a ladder under the puzzle area which cannot be used, i had to noclip to reach the top
will fix
