### ISSUE TITLE
How to increase the text size on the subtitle???

### ISSUE THREAD

**Issue by PretaxRaccoon** [bfeber/HLA-NoVR#77]
![Caption1](https://user-images.githubusercontent.com/130699348/231866050-b09631c7-3890-47c8-be99-55301c7c77b7.jpg)
![Caption2](https://user-images.githubusercontent.com/130699348/231866097-e8f30fac-8664-478f-8982-e479ff958fc7.jpg)
I have a problem reading the text height of 2mm on my 4K screen...I open this case because I see that nobody had reported it yet...I have Half Life Alyx version [Update 1.5.4] +[NoVR mod] with Spanish subtitles activated in a large and wide size but they do not correspond to the screen resolution... is this happening to anyone else? I look forward to your comments and thank you very much for everything!

**Comment by L0v3craft** [comment]
There is an option in the settings about the subtitles size.

**Comment by bfeber** [comment]
Made them bigger. Not that easy to fix otherwise right now. Will be fixed properly when we have the HLA HUD.
