### ISSUE TITLE
Controls from you other than the basic one no longer work after the update

### ISSUE THREAD

**Issue by jflorian27** [bfeber/HLA-NoVR#79]
Recently you made us a different control for the game than the basic one you made.Then even in the game it worked on the keys of both the basic and the new control you made for me.But when I update your mod it doesn't work anymore.Is it possible to tell me what to do so I can always insert my own control for the game after the update.Thank you very much for your help.
Controls that I would like to work every time I update your mod 👍 

"INSERT" "map startup"
"kp_0" "jumpfixed"
"KP_1" "+covermouth"
"uparrow" "+iv_forward"
"downarrow" "+iv_back"
"leftarrow" "+iv_left"
"rightarrow" "+iv_right"
"MOUSE4" "+iv_sprint"
"DEL" "+use;useextra"
"PGUP" "pause"
"PGDN" "noclip"
"KP_4" "inv_flashlight"
"RCTRL" "+iv_duck"
"RSHIFT" "+iv_reload"

**Comment by bfeber** [comment]
If you can be a bit patient then you can wait until I'm done with adding rebinding so you can do it yourself

**Comment by bfeber** [comment]
See new controls section in the README
