### ISSUE TITLE
Mouse movement speed on ultrawide monitor

### ISSUE THREAD

**Issue by dbfx1965** [bfeber/HLA-NoVR#81]
Is there a way to increase mouse movement speed when using ultra wide monitor?

**Comment by bfeber** [comment]
See new controls section in the README

**Comment by dbfx1965** [comment]
Thanks Bjorn,
I changed the bindings.lua for MOUSE_SENSITIVITY = 100.0 from 50 and 100% working 🥇

**Comment by bfeber** [comment]
Great! I'm going to add a graphical launcher in the future where you'll be able to change all kinds of stuff for the mod, including bindings.
