### ISSUE TITLE
Throwing an object, immediately fires on that object

### ISSUE THREAD

**Issue by DragonFlye** [bfeber/HLA-NoVR#85]
With the latest update, if you want to throw i.e. a fuelcan at something, it's immediately followed by shooting at it, instead of only throwing it. This results in immideate death.

**Comment by SpaceMageWhatever** [comment]
yes i had that happen on a controller too but i just thought it was my own fault as im playing with anti micro to fake the controller support, i also disable the mouse so i didnt bother reporting this, anyway its kinda funny, im like a crazed kleptomaniac who HAS to fire a shot whenever i pick something up xD

**Comment by bfeber** [comment]
What's the last version this didn't happen on?

**Comment by DragonFlye** [comment]
Yes, latest one, released a few hours ago. Does not happen on v6.1

**Comment by DragonFlye** [comment]
Fixed, with latest release (2 hours ago), Thanx!
