### ISSUE TITLE
When Objects Collide, With Other Things, They Freeze in Mid Air and Cannot Be Picked Up Anymore

### ISSUE THREAD

**Issue by SpaceMageWhatever** [bfeber/HLA-NoVR#92]
just pick up something and shove it into the walls or into other things and it will freeze in mid air

is this a source engine 2 problem, is this not fixable?

**Comment by bfeber** [comment]
Gravity gloves bug currently

**Comment by Spider-Man1212** [comment]
Any update on this?

**Comment by bfeber** [comment]
I just said Im working on it

**Comment by bfeber** [comment]
fixed
