### ISSUE TITLE
Crash on death

### ISSUE THREAD

**Issue by grimmute** [bfeber/HLA-NoVR#99]
Just updated to [latest](https://github.com/bfeber/HLA-NoVR/commit/dcdde8861bed72cb8560f5fbe54cec208047bf33) from a commit from yesterday (14 April). It started crashing to desktop every time I die.

**Comment by bfeber** [comment]
Even on a new save?

**Comment by billyboybob** [comment]
I tested it a bit ago on a new save by jumping off a building, it crashed for me also.

**Comment by grimmute** [comment]
For me it hasn't crashed again since I passed the chapter I was at.
